development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
#   timeout: 5000

# default: &default
#   adapter: mysql2
#   encoding: utf8
#   host: localhost
#   username: root
#   password:

# development:
#   <<: *default
#   database: react_rails_tutorial_development

# sandbox:
#   <<: *default
#   database: react_rails_tutorial_sandbox

# test:
#   <<: *default
#   database: react_rails_tutorial_test

# production:
#   <<: *default
#   database: react_rails_tutorial_production
